version: '3.1'

services:
  wmbot:
    depends_on:
      - wm_bot_db
    build:
      context: .
    environment:
      BOT_NAME: ${BOT_NAME}
      BOT_TOKEN: ${BOT_TOKEN}
    restart: always
  wm_bot_db:
    image: postgres
    restart: always
    ports:
      - '5433:5433'
    expose:
      - '5433'
    environment:
      POSTGRES_DATABASE: "wm-bot-db"
      BOT_DB_USERNAME: ${BOT_DB_USERNAME}
      BOT_DB_PASSWORD: ${BOT_DB_PASSWORD}
    volumes:
      - wm_bot_db:/var/lib/psql
# Names our volume
volumes:
  wm_bot_db: