version: '3.1'

services:
  wmbot:
    depends_on:
      - wm_bot_db
    build:
      context: .
    env_file:
      - ../envForWmBot/env/wm-bot.env
    restart: always
  wm_bot_db:
    image: postgres
    restart: always
    ports:
      - '5433:5432'
    expose:
      - '5432'
    env_file:
      - ../envForWmBot/env/wm-bot-db.env
    volumes:
      - wm_bot_db:/var/lib/psql
# Names our volume
volumes:
  wm_bot_db: