version: '3.1'

services:
  wm_bot_db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    expose:
      - '5432'
    environment:
      POSTGRES_DATABASE: "wm-bot-db"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres