bot:
  username: world_mac_bot
  token: 5518341246:AAFKeTlse8fVQ9sGxyd4-

spring:
  datasource:
    url: jdbc:postgresql://0.0.0.0:5432/postgres?currentSchema=wm_bot
    username: post
    password: postgr
    driverClassName: org.postgresql.Driver